### ISSUE TITLE
Is this guide compatible with for CyberArk On-prem solution or pCloud?

### ISSUE THREAD

**Issue by microsoftsupportguy** [Keyfactor/cyberark-credentialprovider-pam#10]

**Comment by doebrowsk** [comment]
Both on-premise and cloud-hosted instances are compatible with this integration when configured correctly. The main limiting factor will be configuring firewalls or other proxy access methods so that the PAM Provider can reach CyberArk with the desired protocol method and ports.

The SDK-based PAM Provider makes calls to CyberArk using their protocol defined for Credential Providers through the Password SDK.

The Central PAM Provider uses HTTPS calls to a defined API endpoint to request passwords through the Central Credential Provider.
